### ISSUE TITLE
请问选课学期代码是什么？

### ISSUE THREAD

**Issue by WerewolfII** [hidacow/SHU-CourseHelper#1]
我看文本中有例子20205，请问具体是什么意思，规则是什么？

**Comment by hidacow** [comment]
在每次登录选课系统时，网页上会列出并询问要进行操作的学期，如下图所示
![image](https://user-images.githubusercontent.com/68262945/116428101-2fb68f00-a877-11eb-9b23-e105a5f36b4e.png)

其中春季学期的代码是20203，夏季学期的代码是20205
（秋季学期的代码是20201，冬季学期的代码是20202，但无法选择这些学期）
学期代码是由系统规定的，不一定会有规律，不过前四位理论上应该是代表2020学年
本程序能够通过解析网页得到现有学期并让用户选择，用户选择后程序将自动保存选择的学期代码在配置文件中，以便程序自动运行
若想进行重新选择，可以删除"term="后面的学期代码
如果程序检测到配置文件中的学期代码并不在选课系统选择界面列出的学期中，程序也会重新令用户选择
