### ISSUE TITLE
一些问题及建议

### ISSUE THREAD

**Issue by WerewolfII** [hidacow/SHU-CourseHelper#2]
首先在此感谢同学为选课事业做出的贡献。

请问该代码蹲课捡漏的原理是什么呢？是输入选课课程号和教师号不断“点击”选课来实现捡漏的，还是采用先不断查询课程是否已满，发现未满后立即选课的方式呢？

如果第一种的话学校已经做了相应的保护措施，如果频繁点击选课的话会被禁止选课一段时间。
第二种方式的话，根据实践，频繁点击查询按钮是不会导致禁止获取数据的。

期待你的回复，谢谢！

**Comment by hidacow** [comment]
感谢您对于本项目的关注
本项目是开源的，所有功能的具体实现方式您可以通过仔细阅读代码后了解
简单来说，本程序采取您所述的第二种方式

如果您对该项目的改进与优化有兴趣，请提出一些实质性的建议或指出当前程序存在的问题
