### ISSUE TITLE
为 courses.txt 添加注释支持

### ISSUE THREAD

**Issue by Errant404** [hidacow/SHU-CourseHelper#3]
有时候会忘记自己选了哪些课呢

**Comment by hidacow** [comment]
courses.txt的格式参考ini文件，可以使用"#"、";"作为注释标识，仅需确保未注释的行course后的数字连续即可
即使将已选课的课程加入待抢课列表，脚本也能在有余量后尝试选择并得到“已选该课程”的错误信息放弃抢该课程

**Comment by Errant404** [comment]
之前在冬季学期选课时
类似这样的注释好像会导致运行报错
```
#微积分
course2 = 114514
```
